### ISSUE TITLE
 KeyError: 'separator'

### ISSUE THREAD

**Issue by gerroon** [kodaline/cat-formatter#1]
Hi

There seems to be an error with the plugin.  

CC running on Ubuntu, using Ollama mistral/orca2

```
cheshire_cat_core  |
cheshire_cat_core  | > Finished chain.
cheshire_cat_core  | [2024-01-03 05:05:48.839] ERROR  cat.mad_hatter.mad_hatter.MadHatter.execute_hook::261 => 'Error in plugin cat_formatter_main::before_cat_sends_message'
cheshire_cat_core  | [2024-01-03 05:05:48.847] ERROR  cat.mad_hatter.mad_hatter.MadHatter.execute_hook::262 => KeyError('separator')
cheshire_cat_core  | Traceback (most recent call last):
cheshire_cat_core  |   File "/app/cat/mad_hatter/mad_hatter.py", line 252, in execute_hook
cheshire_cat_core  |     tea_spoon = hook.function(
cheshire_cat_core  |   File "/app/cat/plugins/cat_formatter_main/cat_formatter.py", line 20, in before_cat_sends_message
cheshire_cat_core  |     separator = "<" + settings["separator"] + ">"
cheshire_cat_core  | KeyError: 'separator'
```

**Comment by kodaline** [comment]
@gerroon be sure to save the plugin settings, sorry, it's an issue due to the missing `settings.json` file
Save the settings' setting "br" as separator
P.s. later on I will add the file by default 
I am also improving the plugin added better settings management so soon will release a new version 

**EDIT**: I pushed the default `settings.json` file so you should not have the issue anymore, let me know if it is solved :)
